export const PLATFORM_VOICE_SEED = [
  { name: 'Puck', style: 'Upbeat', gender: 'Neutral', accent: 'American', age: 'Middle Aged' },
  { name: 'Charon', style: 'Bright', gender: 'Neutral', accent: 'American', age: 'Middle Aged' },
  { name: 'Kore', style: 'Clear', gender: 'Female', accent: 'American', age: 'Young' },
  { name: 'Fenrir', style: 'Distinct', gender: 'Male', accent: 'American', age: 'Middle Aged' },
  { name: 'Leda', style: 'Calm', gender: 'Female', accent: 'American', age: 'Middle Aged' },
  { name: 'Orus', style: 'Clear', gender: 'Male', accent: 'American', age: 'Middle Aged' },
  { name: 'Aoede', style: 'Bright', gender: 'Female', accent: 'American', age: 'Young' },
  { name: 'Callirrhoe', style: 'Calm', gender: 'Female', accent: 'American', age: 'Middle Aged' },
  { name: 'Despina', style: 'Calm', gender: 'Female', accent: 'British', age: 'Young' },
  { name: 'Algieba', style: 'Calm', gender: 'Female', accent: 'British', age: 'Middle Aged' },
  { name: 'Achernar', style: 'Calm', gender: 'Female', accent: 'Indian', age: 'Middle Aged' },
  { name: 'Schedar', style: 'Distinct', gender: 'Male', accent: 'Indian', age: 'Middle Aged' },
  { name: 'Achird', style: 'Distinct', gender: 'Male', accent: 'American', age: 'Young' },
  { name: 'Sadachbia', style: 'Distinct', gender: 'Neutral', accent: 'Australian', age: 'Middle Aged' },
  { name: 'Enceladus', style: 'Distinct', gender: 'Male', accent: 'American', age: 'Middle Aged' },
  { name: 'Algenib', style: 'Distinct', gender: 'Male', accent: 'American', age: 'Young' },
  { name: 'Gacrux', style: 'Distinct', gender: 'Female', accent: 'American', age: 'Middle Aged' },
  { name: 'Zubenelgenubi', style: 'Distinct', gender: 'Male', accent: 'American', age: 'Middle Aged' },
  { name: 'Sadaltager', style: 'Distinct', gender: 'Female', accent: 'American', age: 'Young' },
  { name: 'Rasalgethi', style: 'Distinct', gender: 'Male', accent: 'British', age: 'Middle Aged' },
  { name: 'Pulcherrima', style: 'Bright', gender: 'Female', accent: 'American', age: 'Young' },
  { name: 'Vindemiatrix', style: 'Clear', gender: 'Female', accent: 'American', age: 'Middle Aged' },
  { name: 'Sulafat', style: 'Calm', gender: 'Female', accent: 'American', age: 'Middle Aged' },
];
