/**
 * Legal draft categories and their draft types (subcategories).
 * Used in Create Template / Upload Template form.
 */
export const DRAFT_CATEGORIES = [
  {
    id: 'constitutional_remedies',
    label: '1. Constitutional Remedies',
    description: 'Used for High Courts & Supreme Court',
    draftTypes: [
      'Writ Petition (Article 226)',
      'Writ Petition (Article 32)',
      'Habeas Corpus',
      'Mandamus',
      'Certiorari',
      'Prohibition',
      'Quo Warranto',
      'Public Interest Litigation (PIL)',
      'Contempt Petition',
      'Review Petition',
      'Curative Petition',
    ],
  },
  {
    id: 'civil_court_pleadings',
    label: '2. Civil Court Pleadings',
    description: 'Used in District Courts & High Courts',
    draftTypes: [
      'Plaint',
      'Written Statement',
      'Replication',
      'Counter Claim',
      'Interim Application',
      'Injunction Application',
      'Stay Application',
      'Caveat',
      'Appeal (Civil)',
      'Review Petition',
      'Execution Petition',
      'Affidavit',
      'Evidence Affidavit',
      'Objections',
    ],
  },
  {
    id: 'criminal_court_pleadings',
    label: '3. Criminal Court Pleadings',
    description: 'Used before Magistrate, Sessions, High Court',
    draftTypes: [
      'Criminal Complaint',
      'FIR Draft',
      'Bail Application',
      'Anticipatory Bail',
      'Quashing Petition (482 CrPC)',
      'Discharge Application',
      'Compounding Application',
      'Criminal Appeal',
      'Criminal Revision',
      'Special Leave Petition (Criminal)',
    ],
  },
  {
    id: 'family_court_drafts',
    label: '4. Family Court Drafts',
    description: '',
    draftTypes: [
      'Divorce Petition',
      'Mutual Consent Divorce',
      'Maintenance Application',
      'Domestic Violence Petition',
      'Child Custody',
      'Alimony Application',
      'Restitution of Conjugal Rights',
      'Adoption Petition',
      'Succession Petition',
    ],
  },
  {
    id: 'property_real_estate',
    label: '5. Property & Real Estate Court Drafts',
    description: '',
    draftTypes: [
      'Eviction Petition',
      'Partition Suit',
      'Title Suit',
      'Possession Suit',
      'Injunction Suit',
      'Recovery of Property',
      'Property Appeal',
      'Declaration Suit',
    ],
  },
  {
    id: 'corporate_commercial',
    label: '6. Corporate & Commercial Court Drafts',
    description: '',
    draftTypes: [
      'Commercial Suit',
      'Summary Suit',
      'Arbitration Petition (Sec 9)',
      'Arbitration Appointment (Sec 11)',
      'Arbitration Challenge (Sec 34)',
      'Commercial Appeal',
      'Shareholder Dispute',
      'Contract Enforcement Suit',
    ],
  },
  {
    id: 'labour_service',
    label: '7. Labour & Service Law Drafts',
    description: '',
    draftTypes: [
      'Labour Court Petition',
      'Industrial Dispute',
      'Termination Challenge',
      'Salary Recovery',
      'PF & Gratuity Claim',
      'Service Writ',
      'Promotion Dispute',
      'Transfer Challenge',
    ],
  },
  {
    id: 'tax_revenue',
    label: '8. Tax & Revenue Court Drafts',
    description: '',
    draftTypes: [
      'Income Tax Appeal',
      'GST Appeal',
      'Customs Appeal',
      'Excise Appeal',
      'Show Cause Reply',
      'Tax Recovery Stay',
      'Tax Writ Petition',
    ],
  },
  {
    id: 'insolvency_banking',
    label: '9. Insolvency & Banking Drafts',
    description: '',
    draftTypes: [
      'Section 7 IBC Petition',
      'Section 9 IBC Petition',
      'Section 10 IBC Petition',
      'DRT Application',
      'SARFAESI Challenge',
      'Bank Recovery Suit',
      'OTS Application',
      'NCLT Petition',
      'NCLAT Appeal',
    ],
  },
  {
    id: 'consumer_court',
    label: '10. Consumer Court Drafts',
    description: '',
    draftTypes: [
      'Consumer Complaint',
      'Refund Claim',
      'Deficiency of Service',
      'Consumer Appeal',
      'Execution Petition',
    ],
  },
  {
    id: 'special_tribunal',
    label: '11. Special Tribunal Drafts',
    description: '',
    draftTypes: [
      'NGT Petition',
      'CAT Petition',
      'SEBI Appeal',
      'FEMA Appeal',
      'ED Challenge',
      'PMLA Petition',
      'CBI Matter',
    ],
  },
  {
    id: 'interim_miscellaneous',
    label: '12. Interim & Miscellaneous Drafts',
    description: 'These appear in every case',
    draftTypes: [
      'Stay Application',
      'Interim Relief',
      'Amendment Application',
      'Condonation of Delay',
      'Restoration Application',
      'Withdrawal Application',
      'Substitution Application',
      'Recall Application',
      'IA (Interlocutory Application)',
    ],
  },
  {
    id: 'appeals_higher_court',
    label: '13. Appeals & Higher Court Drafts',
    description: '',
    draftTypes: [
      'Civil Appeal',
      'Criminal Appeal',
      'SLP (Civil)',
      'SLP (Criminal)',
      'Review',
      'Curative',
      'Transfer Petition',
    ],
  },
];
